from pathlib import Path
import re, html, json
root=Path(__file__).parent

def inline(s):
    s=html.escape(s)
    s=re.sub(r'\[([^\]]+)\]\(([^)]+)\)',r'<a href="\2">\1</a>',s)
    s=re.sub(r'\*\*(.+?)\*\*',r'<strong>\1</strong>',s)
    s=re.sub(r'\*(.+?)\*',r'<em>\1</em>',s)
    return s
blocks=[]
for block in (root/'article.md').read_text().strip().split('\n\n'):
    if block.startswith('# '):
        title=block[2:];blocks.append('<h1>'+inline(title)+'</h1>')
    elif block.startswith('## '):
        label=block[3:];blocks.append('<h2>'+inline(label)+'</h2>')
    elif block.startswith('| '):
        rows=[r.strip().strip('|').split('|') for r in block.splitlines()]
        blocks.append('<div class="table-wrap"><table><thead><tr>'+''.join('<th>'+inline(c.strip())+'</th>' for c in rows[0])+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+inline(c.strip())+'</td>' for c in r)+'</tr>' for r in rows[2:])+'</tbody></table></div>')
    elif block.startswith('> '): blocks.append('<aside>'+inline(block[2:])+'</aside>')
    elif block.startswith('- '):blocks.append('<ul>'+''.join('<li>'+inline(x[2:])+'</li>' for x in block.splitlines())+'</ul>')
    elif block.startswith('!['):
        m=re.fullmatch(r'!\[(.*?)\]\((.*?)\)',block);alt,url=m.groups();cls='overview' if 'overview' in url else 'screen'
        blocks.append(f'<figure class="{cls}"><a href="{url}" target="_blank"><img src="{url}" alt="{html.escape(alt)}" loading="lazy"></a></figure>')
    else:blocks.append('<p>'+inline(block.replace('\n',' '))+'</p>')
style='''.table-wrap{overflow-x:auto;margin:26px 0}table{border-collapse:collapse;width:100%;font-size:16px;line-height:1.6}th,td{text-align:left;padding:13px 12px;border-bottom:1px solid #dce7eb}th{background:#eef6fa;color:#103b50}h1{line-height:1.18!important}p,li{line-height:1.8!important}*{box-sizing:border-box}body{margin:0;background:#f5f8fb;color:#233443;font-family:-apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif;-webkit-font-smoothing:antialiased}header{max-width:1040px;margin:0 auto;padding:36px 40px 24px;display:flex;align-items:center;gap:14px;font-size:14px;color:#526879}header img{width:44px;height:44px;border-radius:11px}header b{font-size:20px;color:#123e55}header span{margin-left:auto}main{max-width:1040px;margin:auto;background:white;padding:54px 88px 72px;border-top:4px solid #08759f}h1{font-size:42px;line-height:1.4;letter-spacing:-1px;color:#103b50;margin:0 0 30px}h2{font-size:27px;line-height:1.5;color:#103b50;margin:58px 0 20px;padding-top:20px;border-top:1px solid #dce7eb}p,li{font-size:18px;line-height:1.95}p{margin:20px 0}strong{color:#163e53;font-weight:650}a{color:#086e99;text-underline-offset:4px;text-decoration-thickness:1px;overflow-wrap:anywhere}aside{background:#eef6fa;border-left:3px solid #167aa0;padding:16px 20px;font-size:14px;line-height:1.9;color:#526675;margin:28px 0}ul{padding-left:24px}li{padding-left:4px;margin:7px 0}figure{margin:32px 0 16px}figure img{display:block;width:100%;height:auto}figure.screen{max-width:385px;margin:34px auto 14px;border:1px solid #dae3e8;border-radius:22px;overflow:hidden;box-shadow:0 12px 28px #163e530d}p:has(>em:only-child){font-size:14px;line-height:1.8;color:#5d7080;margin:10px 0 30px;text-align:center}em{font-style:normal}footer{max-width:1040px;margin:auto;padding:26px 40px 48px;color:#6c7d89;font-size:13px;line-height:1.8}@media(max-width:650px){header{padding:20px;gap:10px}header span{font-size:12px}main{padding:28px 22px 40px}h1{font-size:29px;letter-spacing:0}h2{font-size:23px;margin-top:44px}p,li{font-size:17px;line-height:1.95}aside{padding:14px;font-size:13px}figure.screen{max-width:100%;border-radius:16px}footer{padding:24px 22px}}'''
desc='Compare steel prices per kg, metre and piece with a worked flat-bar example, delivery-cost comparison and a practical quote checklist.'
(root/'index.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+html.escape(title)+'</title><meta name="description" content="'+desc+'"><style>'+style+'</style></head><body><header><img src="assets/app-icon.png" alt="SteelFlow icon"><b>SteelFlow</b><span>FIELD NOTES · SEP 2026</span></header><main>'+''.join(blocks)+'</main><footer>Screenshots: SteelFlow 1.1.0 (13), iOS 26.5 simulator. Demo routes display actual app views without the main tab shell. All customer and pricing data is fictional.<br>Click any image to open the original. Editorial draft, not yet published.</footer></body></html>')
items=[('home','Choose a profile','Start with the cross-section'),('calculation','Check the weight','Use dimensions and quantity'),('materials','Check the material','Review the density assumption'),('projects','Organise the work','Keep quotes in projects'),('project','Review the totals','Bring the line items together'),('quote','Preview the PDF','Check before sharing')]
css='''*{box-sizing:border-box}body{margin:0;font-family:-apple-system,"PingFang SC",sans-serif;background:#eef5f9;color:#123c51}.board{width:2400px;padding:86px 100px 64px;background:linear-gradient(155deg,#e7f3fb,#f7fafc 46%,#e4f0f5)}header{display:flex;align-items:center;gap:38px;margin-bottom:52px}header img{width:150px;height:150px;border-radius:34px}h1{font-size:72px;margin:0 0 18px;line-height:1.2;letter-spacing:1px}header p{font-size:34px;color:#4f6c7d;margin:0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:58px 54px}.panel h2{font-size:38px;line-height:1.25;margin:0 0 12px;display:flex;gap:20px;align-items:center}.panel b{font-size:29px;color:#08739b;border:2px solid #82b6ca;padding:8px 12px;border-radius:12px}.panel p{font-size:29px;margin:0 0 22px;color:#557080}.screen{width:100%;display:block;border:6px solid white;border-radius:40px;box-shadow:0 16px 34px #224c5d12}.foot{font-size:27px;color:#5c7481;margin:54px 0 0;line-height:1.65}.foot strong{color:#194c65}'''
cards=''.join(f'<section class="panel"><h2><b>{i:02d}</b>{name}</h2><p>{sub}</p><img class="screen" src="screenshots/{f}.png" alt="{name} app screenshot"></section>' for i,(f,name,sub) in enumerate(items,1))
(root/'collage.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><title>SteelFlow workflow overview</title><style>'+css+'</style><div class="board"><header><img src="assets/app-icon.png"><div><h1>From dimensions to a PDF quote</h1><p>SteelFlow · Weight / Pricing / Projects / PDF</p></div></header><div class="grid">'+cards+'</div><p class="foot"><strong>Real app screens · 1.1.0</strong>　Captured in an iPhone simulator using demo routes.<br>Fictional projects, customers and prices. Not live market data.</p></div></html>')
(root/'seo.json').write_text(json.dumps({'title':title,'description':desc,'suggestedSlug':'compare-steel-prices-per-kg-metre-piece','primaryKeyword':'compare steel prices per kg per metre','author':'SteelFlow developer','language':'en','publicationState':'draft','canonical':None},indent=2))
print('Generated English article and collage HTML')
